CeuAzul/ADR

- ADR/Analysis/Performance/Motor.py
Motor now has static_thrust and linear_thrust_decay, from which the motor can return the thrust calculated according to a given velocity.
> Improve Motor() class

- ADR/Analysis/Performance/Takeoff.py
- ADR/Analysis/Performance/test_Takeoff.py
Make the file a method that is imported and used from an outside test_Takeoff.py, which passes the Plane instance and the takeoff_parameters.
> Turn Takeoff analysis into an MTOW estimator

- ADR/Components/Aerodynamic_components/Aerodynamic_surface.py
- ADR/Components/Aerodynamic_components/Airfoil.py
- ADR/Methods/VLM/pyVLM/pyvlm/vlm.py
They were on pyVLM and on airfoil mass estimative.
> Remove plots and prints from inside code

- ADR/Analysis/Performance/Takeoff.py
- ADR/Analysis/Performance/test_Takeoff.py
This way the attributes of the object can be accessed from outside and plotted, printed, etc.
> Change Takeoff analysis to a class

- ADR/Analysis/Stability/FlightStability/Container.py
- ADR/Analysis/Stability/FlightStability/FlightStability.py
- ADR/Analysis/Stability/FlightStability/test_FlightStability.py
- ADR/Components/Component.py
- ADR/Components/Points/CA.py
- ADR/Components/Points/CG.py
> Varying cg

- ADR/Analysis/Performance/Takeoff.py
- ADR/Analysis/Performance/test_Takeoff.py
- ADR/Analysis/Stability/FlightStability/test_FlightStability.py
- ADR/main.py
- ADR/parameters.py
The parameters.py file stores all the data needed for the analysis, including plane data, takeoff data and stability data.
All the test_X analysis files now use the same parameters from parameters.py, preventing problems related to different analysis using different data.
> Introduce parameters file

- ADR/Analysis/Stability/FlightStability/test_FlightStability.py
> Use standard Matplotlib format

- ADR/Analysis/Stability/FlightStability/FlightStability.py
- ADR/Components/Aerodynamic_components/Aerodynamic_surface.py
Now when out of tail range, None values are given to CM_alpha_CG
> Fix CM_alpha erroneous values

- ADR/Components/Aerodynamic_components/Aerodynamic_section.py
- ADR/Components/Aerodynamic_components/Aerodynamic_surface.py
Based on @joaodreveck and Raymer formulas.
Fix #37
> Fix area and MAC calculation

- ADR/Components/Aerodynamic_components/Aerodynamic_surface.py
This way developers can run internal VLM for debug without having to use Windows or compile AVL on Linux.
> Creates option to use internal python VLM or external AVL

- ADR/Analysis/Performance/Power.py
- ADR/Analysis/Performance/Takeoff.py
- ADR/Analysis/Performance/test_Power.py
- ADR/Analysis/Performance/test_Takeoff.py
- ADR/Analysis/Stability/FlightStability/FlightStability.py
- ADR/Analysis/Stability/FlightStability/test_FlightStability.py
- ADR/Components/Aerodynamic_components/Aerodynamic_surface.py
- ADR/Components/Aerodynamic_components/HS.py
- ADR/Components/Plane.py
- ADR/Core/data_manipulation.py
- ADR/main.py
- ADR/parameters.py
Ok, don't kill me for the size of the commit. The fact is: everybody had to change.
Min e Max alphas for power analysis and for trimm analysis are now implemented and being used in a lot of places.
We can also set an alpha for the plane and it auto updates it's aerodynamic surfaces, trimmed!
Everything working again.
> Trimm analysis

- ADR/Analysis/Stability/FlightStability/FlightStability.py
- ADR/Checkers/StaticMargin.py
- ADR/Checkers/TrimmRange.py
- ADR/Components/Plane.py
- ADR/main.py
The checkers are classes  instantiated and called by the Main to check if a series of conditions are met.
They pass, don't pass or score an aircraft.
Solves #62 and #63
> Checkers implementation

- ADR/Checkers/Scoreboard.py
- ADR/Components/Plane.py
- ADR/main.py
The Assassin (or not) checks if the plane has met it's criterias. If so, the airplane receives an score, if not, it dies.
Solves #61
> Score and Kill implemented

- ADR/Analysis/Performance/test_Power.py
- ADR/Analysis/Performance/test_Takeoff.py
- ADR/Analysis/Stability/FlightStability/FlightStability.py
- ADR/Analysis/Stability/FlightStability/test_FlightStability.py
- ADR/main.py
Now main.py calls for plots if plot enabled.
Plot functions inside test files are used for plotting.
> Renew plot structure

- ADR/Analysis/Stability/FlightStability/FlightStability.py
- ADR/Analysis/Stability/FlightStability/test_FlightStability.py
- ADR/Components/Aerodynamic_components/Aerodynamic_surface.py
- ADR/Components/Aerodynamic_components/HS.py
- ADR/Components/Plane.py
- ADR/main.py
Now they calculate their own alpha and (for the HS) incidence range.
Solves #75
> Implement range setters and getters on Plane and HS

- ADR/Analysis/Stability/FlightStability/FlightStability.py
- ADR/Checkers/Dimensions.py
- ADR/Checkers/Scoreboard.py
- ADR/Components/Plane.py
- ADR/main.py
Checks if the dimensions are inside the SAE restrictions.
> Dimensions checker implemented

- ADR/Analysis/Performance/Power.py
- ADR/Checkers/Dimensions.py
- ADR/Components/Plane.py
- ADR/main.py
- ADR/parameters_optmizer.py
- Fix alpha_max formula
- Limit Power analysis to stall alphas
- Fix total dimension formula 
- Force HS' x position to fit dimension restriction
- Make biplane default on optmizer
> Power analysis and dimension-checker fixes

- ADR/Analysis/Stability/FlightStability/FlightStability.py
Previous method was inconsistent
> Use root finder to find alpha_trimms

- ADR/Analysis/Performance/Takeoff.py
The analysis now checks if the velocity at the end of the road (V_takeoff) is greater than V_stall and if the Thrust is greater than the Drag (to go forward).
> Include stall and power analysis on Takeoff

- ADR/Analysis/Performance/Power.py
- ADR/Checkers/Scoreboard.py
- ADR/Components/Plane.py
- ADR/main.py
- ADR/optmizer.py
- ADR/parameters_optmizer.py
Now main.py use parameters.py if an empty optmizer list is passed to the function, and use parameters_optmizer.py if a list is passed. This allows main.py to be used as needed.
Also includes V_takeoff as Plane attribute (was missing from another commit) and removes bad power analysis (no roots does not necessarily means no power excess, just small velocity range).
> Optmizer and main improvements

- ADR/Core/insert_genes.py
- ADR/main.py
- ADR/my_own_parameters.py
- ADR/optmizer.py
- ADR/parameters.py
- ADR/who_you_gonna_call.py
Also: 
- fix ADR import on parameters
- by default use genes and own_parameters
- change default genes
- parametrize optmizer
- allow who_you_gonna_call to call optmizer with settings
> Fix genes insert and improve caller

- ADR/Analysis/Aerodynamics/AerodynamicPlots.py
- ADR/Components/Plane.py
- ADR/main.py
Including CL_alpha, CD_alpha, CL_CD and CL_alpha of the surfaces
> Generate CD_alpha for the plane and plot aerodynamic curves

- .travis.yml
> Create CI/CD pipeline

- ADR/Methods/FundamentalEquations.py
- ADR/Methods/tests/test_FundamentalEquations.py
- Implement structure
- Implement test for lift function
@joaofoes and @CassianoMontibeller could you take from here?
> Implement tests on fundamental equations (new)

- ADR/World/Constants/Constants.py
- ADR/World/tests/test_Constants.py
I've updated the gravity_constant function and added a new test for it.
> gravity_constant function update and new test

- ADR/Components/Aerodynamic_components/Airfoil.py
Remove unused import
Breakes long lines
Remove unused variables
> Cleaning in the Airfoil file

- ADR/Components/Aerodynamic_components/tests/test_Aerodynamic_section.py
Added test for calc_area and calc_MAC functions
> Add test for functions in Aerodynamic_section

- ADR/Components/Aerodynamic_components/tests/test_Airfoil.py
I've created tests for the functional functions in airfoil class.
> Add test for Airfoil Class

- .travis.yml
- Add __init__.py files so pytest finds all project folders
- Add coverage and coveralls script to travis.yml so coverage badge can be created
> Add coverage and coveralls to travis

- .travis.yml
Add script to download AVL from https://gitlab.com/relmendorp/avl and compile it
> Make travis compile AVL

- ADR/Analysis/Performance/Power.py
- ADR/Analysis/Performance/Takeoff.py
- ADR/Components/Aerodynamic_components/tests/test_VS.py
- ADR/Components/Aerodynamic_components/tests/test_Wing.py
- ADR/Components/Plane.py
- ADR/Core/import_functions.py
- ADR/Methods/VLM/AVL/avlwrapper_io.py
- ADR/main.py
> Remove unused classes, functions and imports

- ADR/__init__.py
- ADR/analyzer.py
- ADR/main.py
- Exposes analyzer at ADR.analyzer
- Analyzer expects plane_parameters and performance_parameters
Solves #165
> Creates general analyzer function (extracted from main)

- ADR/Components/tests/test_Component.py
Ok, so... For this specific test i wasn't quite sure the correct way to approach it. So if it wasn't supposed to be like this would be glad to know!
> Add test for component class

- ADR/Checkers/tests/test_StaticMargin.py
> Add test for Static Margin checker

- ADR/Checkers/tests/test_TrimmRange.py
> Add test for TrimmRangeChecker

- ADR/Analysis/Stability/FlightStability/tests/test_FlightStability.py
> Add test for FlightStability class

- ADR/Checkers/tests/test_Scoreboard.py
> Add test for MaybeAnAssassin

- ADR/Components/Points/tests/test_CA.py
- ADR/Components/Points/tests/test_CG.py
- ADR/Components/Points/tests/test_TPR.py
> Tests for CA, CG and TPR classes

- tests/Components/test_AttachedComponent.py
- tests/Components/test_BaseComponent.py
- tests/Components/test_FreeBody.py
Add fixtures, instantiation tests, and state-setting tests for the following classes:
- BaseComponent
- AttachedComponent
- FreeBody
Contributes to #219, #218 ahd #217
> Instantiation tests for components

- docs/Components/BaseComponent.md
- Explains usage of the class
- Explains its instantiation
> Add docs for BaseComponent

- docs/Components/FreeBody.md
- Explains usage of the class
- Explains its instantiation
Complements #218
> Add docs for FreeBody class

- docs/Components/AttachedComponent.md
- Explain usage of the class
- Explain its instantiation
> Add docs for AttachedComponent

- docs/World/Ambient.md
- docs/World/constants.md
- tests/World/test_Ambient.py
- tests/World/test_constants.py
> Add tests and Docs for Constants and Ambient files

- tests/Components/test_AttachedComponent.py
- tests/Components/test_BaseComponent.py
- tests/Components/test_FreeBody.py
Add tests for reset_state functions on BaseComponent, FreeBody and AttachedComponent.
Contributes to #217 #219 and #218
> Add test for reset_state methods

- docs/Components/AttachedComponent.md
- docs/Components/BaseComponent.md
- docs/Components/FreeBody.md
Add docs for reset_state functions on BaseComponent, FreeBody and AttachedComponent.
Contributes to #217 #219 and #218.
> Add docs for reset_state methods

- tests/helper_functions/test_algebric.py
Add tests to:
- translate
- rotate
- transform (rotate+translate)
> Add tests to algebric helper functions

- adr/Components/BaseComponent.py
- tests/Components/test_BaseComponent.py
- tests/Components/test_FreeBody.py
Contributes to #217 and #218
Covers all force/moment methods.
> Add tests for methods involving calculation of moments and forces on components

- tests/helper_functions/test_algebric.py
- component_vector_in_absolute_frame
- component_vector_coords_in_absolute_frame
Contributes to #214
> Add tests to remaining algebric helper functions

- docs/helper functions/algebric.md
> Add docs to algebric helper functions

- tests/Components/test_FreeBody.py
> Add test to move method in FreeBody

- docs/Components/FreeBody.md
> Add docs to move method on FreeBody

- tests/Components/test_BaseComponent.py
The test was testing the force method, not the moment one, and also asserting from it, passing silently.
> Fix add_external_moment_function method test

- docs/Components/BaseComponent.md
- docs/Components/FreeBody.md
Cover all related methods yet.
Contributes to #218 and #217
> Add docs to force and moment methods on BaseComponent and FreeBody

- adr/Components/Aerodynamic/AerodynamicSurface.py
- adr/Components/Aerodynamic/Flap.py
- adr/Components/Aerodynamic/RectangularAerodynamicSurface.py
- adr/Components/Aerodynamic/RectangularHorizontalStabilizer.py
- adr/Components/Aerodynamic/RectangularWing.py
- adr/Components/Aerodynamic/__init__.py
- adr/Components/Auxiliary/LandingGear.py
- adr/Components/Auxiliary/Payload.py
- adr/Components/Auxiliary/__init__.py
- adr/Components/Powertrain/Motor.py
- adr/Components/Powertrain/SimpleMotor.py
- adr/Components/Powertrain/__init__.py
- adr/Components/__init__.py
- adr/Methods/Aerodynamic/__init__.py
- adr/Methods/Aerodynamic/aerodynamic_fundamental_equations.py
- adr/Methods/Powertrain/__init__.py
- adr/Methods/Powertrain/thrust_equations.py
- adr/Methods/__init__.py
- adr/World/Aerodynamic/__init__.py
- adr/World/Aerodynamic/coefficients_data.py
- adr/World/__init__.py
Add the following components to ADR:
- AerodynamicSurface
- RectangularAerodynamicSurface
- RectangularWing
- RectangularHorizontalStabilizer
- Flap
- LandingGear
- Payload
- Motor
- SimpleMotor
Also, add basic equations to calculate for aerodynamic properties and thrust.
> Add basic plane components to ADR

- adr/Components/Auxiliary/LandingGear.py
- docs/Components/Auxiliary/LandingGear.md
- mkdocs.yml
- tests/Components/Auxiliary/test_LandingGear.py
Fixes #268 
Testing everything on the component:
- instantiation
- floor_contact_point property
- gear_reaction method
- gear_friction method
Adding detailed information on using the component.
> Add tests and docs for LandingGear component
